### ISSUE TITLE
Terraria Checklist error

### ISSUE THREAD

**Issue by Ploxl** [ewauq/ewauq.github.io#1]
Since Journey's End meteors no longer spawn after destroying shadow orb / crimson heart. They spawn after either the Eater of Worlds or Brain of Cthulhu is killed. (2nd point in chapter II: Corruption)

**Comment by ewauq** [comment]
Thank you for the report, I will look into it soon.

**Comment by ewauq** [comment]
Will be fixed in the next update. Sorry for the delay.
